version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '80:80' 
    networks:
      - app-network
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5022:5022' 
    networks:
      - app-network
    environment:
      - MONGODB_URL=mongodb://host.docker.internal:27017/eventsRegistration 
      - PORT=5022
    depends_on:
      - mongo
  
  mongo: 
    image: mongo
    restart: always
    ports:
      - "27017:27017"

networks:
  app-network:
    driver: bridge